version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - data-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
  web:
    build: .
    volumes:
      - .:/amc1
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  data-volume:
